version: '3'
services:
  frontenddebug:
    container_name: frontenddebug
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - '1234:1234'
  frontendprod:
    container_name: frontendprod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'

